language: go

go:
  - 1.5.3
  - 1.6

sudo: false

install:
  - go get -t -d -v ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/onsi/ginkgo/ginkgo
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/modocache/gover
  - go get -u github.com/axw/gocov/gocov
  - go get -u github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - ginkgo -r -cover --randomizeAllSpecs --randomizeSuites --failOnPending --trace --race --progress
  - rm api2go-gorm-gin-crud-example.coverprofile
  - bash scripts/fmtpolice
  - gover
